//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// PEFrontier.rc에서 사용되고 있습니다.
//
#define IDC_BTN_CONTINUE                3
#define IDC_BTN_HALT                    4
#define IDC_BTN_IGNORE                  5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_PEFrontierTYPE              130
#define ID_WINDOW_MANAGER               131
#define ID_DOCK_PRJMGR                  133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define IDM_VIEW_PROC_VAS               138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_DOCK_PRJMGR                 155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_PRJMGR_DEFAULT        174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_DOCK_MODULE                  185
#define ID_DOCK_THREAD                  186
#define ID_DOCK_OUTPUT                  187
#define ID_DOCK_REGISTER                188
#define ID_DOCK_BREAK                   189
#define IDR_DOCK_BOOKMARK               190
#define IDR_PEDASM_TYPE                 200
#define IDR_PESOURCE_TYPE               201
#define IDR_PETYPE_VIEW_VMEM            202
#define ID_DOCK_CALLSTACK               203
#define IDR_DOCK_BREAKPOINT             204
#define IDR_POPUP_PRJMGR_BACKBROUND     250
#define IDR_POPUP_PRJMGR_MODULE         251
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_PE_FORMAT                   310
#define IDD_MEM_DUMP                    311
#define IDB_DBG_BREAK                   312
#define IDD_ENV_CONFIG                  313
#define IDB_DOCK_THREAD                 315
#define IDB_DOCK_MODULE                 317
#define IDB_DOCK_PRJMNG                 318
#define IDR_TOOLBAR_DEBUG               319
#define IDD_NEW_DBGPRJ                  320
#define IDR_PE_HTML                     321
#define IDB_VIEW_VMEM                   322
#define IDD_PROC_LIST                   323
#define IDD_EXCEPT_INFO                 324
#define IDR_TOOLBAR_EXPLORE             325
#define IDD_SIMPLE_INPUT                326
#define IDC_EDT_PRJ_NAME                1000
#define IDC_EDT_HEXA                    1000
#define IDC_MDB_PDB_PATH                1001
#define IDC_EDIT_COLUMN                 1001
#define IDC_EDT_ARGS                    1001
#define IDC_MDB_PRJ_PATH                1002
#define IDC_LV_PROCESS                  1002
#define IDC_MDB_EXE_PATH                1003
#define IDC_BTN_REFRESH                 1003
#define IDC_RDO_PEFILE                  1004
#define IDC_RDO_PROCESS                 1005
#define IDC_ICON_WARN                   1005
#define IDC_EDT_MSG                     1006
#define IDC_LV_DETAIL                   1007
#define IDC_EDT_INPUT                   1008
#define IDM_ENV_CONFIG                  32771
#define IDM_DEBUG_START                 32772
#define IDM_DEBUG_BREAK_ALL             32773
#define IDM_DEBUG_STOP                  32774
#define IDM_DEBUG_RUN_DIRECT            32775
#define IDM_DEBUG_RESTART               32776
#define IDM_DEBUG_PROCESS               32777
#define IDM_DEBUG_CONTINUE              32778
#define IDM_DEBUG_STEP_IN               32779
#define IDM_DEBUG_STEP_OVER             32780
#define IDM_DEBUG_STEP_OUT              32781
#define IDM_DEBUG_RUN2CURSOR            32782
#define IDM_DEBUG_SET_BREAK             32783
#define IDM_DEBUG_DELETE_ALL_BREAK      32784
#define IDM_DEBUG_DISABLE_ALL_BREAK     32785
#define IDM_DEBUG_BREAK_ENTRY           32786
#define IDM_DEBUG_BREAK_RTLSTARTUP      32887
#define IDM_EXPLR_GO_BACK               32788
#define IDM_EXPLR_GO_FORE               32789
#define IDM_EXPLR_EDIT_GOTO             32790
#define IDM_EXPLR_GO_ADDR               32791
#define IDM_EXPLR_GO_CURPOS             32792
#define IDM_EXPLR_GO_ENTPTR             32793
#define IDM_EXPLR_BM_TOGGLE             32794
#define IDM_EXPLR_BM_PREV               32795
#define IDM_EXPLR_BM_NEXT               32796
#define IDM_EXPLR_BM_CLEAR              32797
#define IDM_DEBUG_GOTO_CURBP            32798
#define IDM_DEBUG_SAVE_ASM              32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
